language: en
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!pnpm-lock.yaml"
    - "!*.md"
    - "!dist/**"
    - "!.next/**"
  tools:
    eslint:
      enabled: true
    biome:
      enabled: false
chat:
  auto_reply: true
