export const ROUTE_LABELS: Record<string, string> = {
    home: 'Ana Sayfa',
    site: 'Site',
    generate: 'Vibe Üretim',
    pages: 'Sayfalar',
    builder: 'Sayfa Editörü',
    domains: 'Domainler',
    seo: 'SEO',
    publish: 'Yayınla',
    modules: 'Modüller',
    offer: 'Teklif Alma',
    contact: 'İletişim',
    hr: 'İK',
    'job-posts': 'İş İlanları',
    applications: 'Başvurular',
    legal: 'Yasal Metinler',
    inbox: 'Gelen Kutusu',
    offers: 'Teklifler',
    analytics: 'Analitik',
    settings: 'Ayarlar',
    users: 'Kullanıcılar',
    billing: 'Fatura & Plan',
    notifications: 'Bildirimler',
    supabase: 'Supabase',
    admin: 'Yönetici',
    sites: 'Site Yönetimi',
};
