import {
    Globe,
    Package,
    Inbox,
    BarChart2,
    Settings,
    FileText,
    Pencil,
    Sparkles,
    Link2,
    Search,
    Send,
    Briefcase,
    Users,
    Scale,
    Zap,
    MessageSquare,
    LayoutDashboard,
    Database,
    FileBarChart,
    BarChart3,
    ScrollText,
    Shield,
    Key,
    HardDrive,
    Building2,
    SlidersHorizontal,
    CreditCard,
    Bell,
    Activity,
} from 'lucide-react';

export const NAV_ICON_SIZE_CLASS = 'h-[18px] w-[18px]';
export const CHILD_ICON_SIZE_CLASS = 'h-[14px] w-[14px]';

export const NavIcons = {
    Globe,
    Package,
    Inbox,
    BarChart2,
    Settings,
    FileText,
    Pencil,
    Sparkles,
    Link2,
    Search,
    Send,
    Briefcase,
    Users,
    Scale,
    Zap,
    MessageSquare,
    LayoutDashboard,
    Database,
    FileBarChart,
    BarChart3,
    ScrollText,
    Shield,
    Key,
    HardDrive,
    Building2,
    SlidersHorizontal,
    CreditCard,
    Bell,
    Activity,
} as const;

export type NavIconName = keyof typeof NavIcons;
